### ISSUE TITLE
How is JProcessing different from importing Processing?

### ISSUE THREAD

**Issue by jeremydouglass** [theGreatestGeniusIntheWorld/JProcessing#2]
> However, if the time comes when you want to implement Processing GUI and use its methods in an existing Java project, or some of the functionality of your project is only supported in Java IDE, or maybe for some other reasons you just have to program in Java, and need simple methods to work with GUI and animation, then JProcessing will be for you.

Could your Readme explain how using JProcessing different from importing the Processing jars directly into a Java project, e.g. with Eclipse?

-  https://github.com/processing/processing-library-template
-  https://stackoverflow.com/questions/21309851/use-processing-in-java-application
-  https://happycoding.io/tutorials/java/processing-in-java

**Comment by KevinLiuxy** [comment]
Hello Jeremy,
Thanks for the email. To be honest, using JProcessing is just like
extending PApplet in processing-core.jar. There's little difference.
Compared to PApplet, the only difference is JProcessing implements the most
frequent-used methods in processing. Methods like 3D rendering and
exporting PDF etc. are not included. Therefore, it's advantage is
performing just like PApplet for most of the time, while only taking
slightly over 1/5 of PApplet's space. It's a light version of PApplet, if
code simplicity is concerned.
(Also, unlike PApplet, JProcessing extends JFrame which gives you more
control over the display window in java)

I'll update Readme to state it more clear. Thankyou for your suggestion.

**Comment by jeremydouglass** [comment]
> I'll update Readme to state it more clear. Thankyou for your suggestion.

Hi @KevinLiuxy -- any chance of an update on that README? I'd like to link to and curate this as part of Processing related resources, but I'm a biit worried that the current README may confuse people, making them believe that Processing can't be used in Java without this -- when it can.

I like that you have just developed a lightweight / simplified interface, which can be an alternative to PApplet -- it would be great if that was made clear.

**Comment by KevinLiuxy** [comment]
It's been updated. I hope it now clarifies everything better. Ask me if further modifications are needed. I'm very glad to help.

**Comment by jeremydouglass** [comment]
Looks great, Kevin -- thanks so much, and thanks again for sharing this.
